### ISSUE TITLE
Enhance readme

### ISSUE THREAD

**Issue by amacado** [devicons/public-upload-to-imgur#1]
Enhance README.md
- [x] License
- [x] Relation to main repo (devicons)
- [x] Usage/Tutorial
- [x] ..?

**Comment by Thomas-Boi** [comment]
Hey @amacado,

I just added the docs and license to this repo. However, I also added an extra feature to accept folders and glob. I'll also have to update it so the output reflects the multiple uploaded file.

My next plan is to update the reference in the devicon repo so it use this repo instead of my old one. I'll also test it to ensure everything is going well.

**Comment by Thomas-Boi** [comment]
Hello @amacado ,

All the functionality has been added and tested to the repo. The workflow now uses the newest version of this action.
